[package]
name = "optimorph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "3.6.0"
pathfinding = "4.1.2"
petgraph = "0.6.3"
thiserror = "1.0.40"
